#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
mknod /dev/hvc0 c 229 0
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

echo -e "__        __   _                            _          _   _ ___ _____ ____  "
echo -e "\ \      / /__| | ___ ___  _ __ ___   ___  | |_ ___   | | | |_ _|_   _| __ ) "
echo -e " \ \ /\ / / _ \ |/ __/ _ \| '_ \` _ \ / _ \ | __/ _ \  | |_| || |  | | |  _ \ "
echo -e "  \ V  V /  __/ | (_| (_) | | | | | |  __/ | || (_) | |  _  || |  | | | |_) |"
echo -e "   \_/\_/ \___|_|\___\___/|_| |_| |_|\___|  \__\___/  |_| |_|___| |_| |____/ "
